### PR TITLE
fixed error onRestart, resolved #24

### LINKED ISSUE #24: fixMusicOnRestart

### PR DESCRIPTION
**Pull request by LohushD**

### CODE REVIEW

File: app/src/main/java/com/company/integer/vkmusic/logic/MusicPlayer.java [hunk 1]
```diff
@@ -45,7 +45,6 @@ public void pause() {
 
     @Override
     public void setPlayList(ArrayList<MusicTrackPOJO> tracks, int position) {
-        player.reset();
```
Comment (AndriyTheProgrammer) [inline app/src/main/java/com/company/integer/vkmusic/logic/MusicPlayer.java:48]: he he
